### ISSUE TITLE
Object functions

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#101]
[ClassLibrary](https://github.com/jjfiv/dalvik-js/blob/master/src/ClassLibrary.js#L5) is now instantiated with an Object constructor. We had been [putting off](https://github.com/jjfiv/dalvik-js/blob/master/src/invoke.js#L58) implementing [Object](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Object.html) methods, but now need to bring that to the forefront, since with multithreading, wait, notify, etc. will all become relevant and need to be implemented in our machine, using our infrastructure.

This issue will likely be linked to subtasks, but the main design questions can go in this thread.

**Comment by jjfiv** [comment]
So this is very tied to getting all features of Threads?

**Comment by etosch** [comment]
Yes, well, mainly synchronization.

BTW I uploaded a homework assignment I had on synchronization. Since it was
homework, it covered a lot of ground. Unfortunately, it uses collections. I
can modify the Java to use an array with synchronized access, as
appropriate.

On Wed, Oct 31, 2012 at 12:22 PM, John Foley notifications@github.comwrote:

> So this is very tied to getting all features of Threads?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/101#issuecomment-9951339.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by jjfiv** [comment]
We've implemented things as we need them; calling this closed for now.
