### ISSUE TITLE
formalize new Thread structure

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#104]
Using some of the information in #91 and the [Java Thread doc](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.html), formalize the new Thread structure and update [global.js](https://github.com/jjfiv/dalvik-js/blob/master/src/global.js) accordingly.

**Comment by jjfiv** [comment]
Thread is now an Instance of java/lang/Thread as appropriate; it should have fields... our internal VMthread is slightly different, but this is currently not an issue.
