### ISSUE TITLE
collections

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#105]
@jjfiv - what would it take to implement collections?

**Comment by jjfiv** [comment]
It looks like collections are heavily written in C/C++, so it would possibly be a lot of Javascript work.

**Comment by etosch** [comment]
So we're not going to be able to call anything that uses LinkedLists, etc?

On Wed, Oct 31, 2012 at 12:17 PM, John Foley notifications@github.comwrote:

> It looks like collections are heavily written in C/C++, so it would
> possibly be a lot of Javascript work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/105#issuecomment-9951127.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by jjfiv** [comment]
Not likely. java.util. was kind of a minefield. I'd be happy to send you the files to look through, but I think it's out of scope for now (short of a few miracles)

**Comment by etosch** [comment]
So did the doppio people not do this?

On Wed, Oct 31, 2012 at 12:21 PM, John Foley notifications@github.comwrote:

> Not likely. java.util. was kind of a minefield. I'd be happy to send you
> the files to look through, but I think it's out of scope for now (short of
> a few miracles)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/105#issuecomment-9951282.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by jjfiv** [comment]
They are using a slightly different JCL; it's possible that the 
non-Dalvik one is less native. I can take a look at this later.

**Comment by emeryberger** [comment]
IIRC they are using GNU Classpath.

## 

Professor Emery Berger
Department of Computer Science
University of Massachusetts, Amherst
www.cs.umass.edu/~emery

**Comment by jjfiv** [comment]
I will see if I can dex and disassemble the collections library via the Doppio instructions later today. Their readme instructs you how to copy the classes from your installed JVM; they don't explicitly suggest Classpath.

I got the impression that Classpath died since the whole OpenJDK thing.
