### ISSUE TITLE
some new tests fail

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#114]
Const_4.dex, Const_class.dex, Const_wide_high16.dex

**Comment by guptha-** [comment]
Please upload the java source and dex. I can try to debug failures.

**Comment by etosch** [comment]
these are still failing on my local copy. also, my changes were overwritten. ive added them back but don't want to push until im sure we have the most recently/accurate code up. what the hell is going on?

**Comment by guptha-** [comment]
Which file(s) were your changes in?

**Comment by jjfiv** [comment]
https://github.com/jjfiv/dalvik-js/commit/1e711874d51e737e4d78b45a8eb54947dc31beae
vmtest/index.html and vmtest/vmtest.js

**Comment by etosch** [comment]
Mine were in vmtest.js and the index.html. These tests mentioned above were
still failing before I added my changes back in. My changes were checked in
and working last night and disappeared in the middle of the night.

On Sun, Nov 4, 2012 at 3:49 PM, guptha- notifications@github.com wrote:

> Which file(s) were your changes in?
> 
> On Sun, Nov 4, 2012 at 3:43 PM, etosch notifications@github.com wrote:
> 
> > these are still failing on my local copy. also, my changes were
> > overwritten. ive added them back but don't want to push until im sure we
> > have the most recently/accurate code up. what the hell is going on?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055130>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055217.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by guptha-** [comment]
I just looked, and my change in vmtest/tests.js has disappeared too.

On Sun, Nov 4, 2012 at 3:52 PM, etosch notifications@github.com wrote:

> Mine were in vmtest.js and the index.html. These tests mentioned above
> were
> still failing before I added my changes back in. My changes were checked
> in
> and working last night and disappeared in the middle of the night.
> 
> On Sun, Nov 4, 2012 at 3:49 PM, guptha- notifications@github.com wrote:
> 
> > Which file(s) were your changes in?
> > 
> > On Sun, Nov 4, 2012 at 3:43 PM, etosch notifications@github.com
> > wrote:
> > 
> > > these are still failing on my local copy. also, my changes were
> > > overwritten. ive added them back but don't want to push until im sure
> > > we
> > > have the most recently/accurate code up. what the hell is going on?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055130>.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055217>.
> 
> ## 
> 
> Emma Tosch
> Graduate Research Assistant, Computational Intelligence Lab, Hampshire
> College
> MS/PhD student, University of Massachusetts, Amherst
> etosch@cs.umass.edu
> http://cs.umass.edu/~etosch
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055253.

**Comment by etosch** [comment]
I clicked on my commit to add my changes back into the version I pulled; if
yours weren't too integrated, you might be able to do that too? You can
click on "raw" to get something easy to copy and paste.

On Sun, Nov 4, 2012 at 3:58 PM, guptha- notifications@github.com wrote:

> I just looked, and my change in vmtest/tests.js has disappeared too.
> 
> On Sun, Nov 4, 2012 at 3:52 PM, etosch notifications@github.com wrote:
> 
> > Mine were in vmtest.js and the index.html. These tests mentioned above
> > were
> > still failing before I added my changes back in. My changes were checked
> > in
> > and working last night and disappeared in the middle of the night.
> > 
> > On Sun, Nov 4, 2012 at 3:49 PM, guptha- notifications@github.com
> > wrote:
> > 
> > > Which file(s) were your changes in?
> > > 
> > > On Sun, Nov 4, 2012 at 3:43 PM, etosch notifications@github.com
> > > wrote:
> > > 
> > > > these are still failing on my local copy. also, my changes were
> > > > overwritten. ive added them back but don't want to push until im
> > > > sure
> > > > we
> > > > have the most recently/accurate code up. what the hell is going on?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055130>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055217>.
> > 
> > ## 
> > 
> > Emma Tosch
> > Graduate Research Assistant, Computational Intelligence Lab, Hampshire
> > College
> > MS/PhD student, University of Massachusetts, Amherst
> > etosch@cs.umass.edu
> > http://cs.umass.edu/~etosch
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055253>.
> 
> On Sun, Nov 4, 2012 at 3:52 PM, etosch notifications@github.com wrote:
> 
> > Mine were in vmtest.js and the index.html. These tests mentioned above
> > were
> > still failing before I added my changes back in. My changes were checked
> > in
> > and working last night and disappeared in the middle of the night.
> > 
> > On Sun, Nov 4, 2012 at 3:49 PM, guptha- notifications@github.com
> > wrote:
> > 
> > > Which file(s) were your changes in?
> > > 
> > > On Sun, Nov 4, 2012 at 3:43 PM, etosch notifications@github.com
> > > wrote:
> > > 
> > > > these are still failing on my local copy. also, my changes were
> > > > overwritten. ive added them back but don't want to push until im
> > > > sure
> > > > we
> > > > have the most recently/accurate code up. what the hell is going on?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055130>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055217>.
> > 
> > ## 
> > 
> > Emma Tosch
> > Graduate Research Assistant, Computational Intelligence Lab, Hampshire
> > College
> > MS/PhD student, University of Massachusetts, Amherst
> > etosch@cs.umass.edu
> > http://cs.umass.edu/~etosch
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055253>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055334.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by guptha-** [comment]
Thankfully, it was a minor change. The next time we do something like this,
we should have a Configuration Librarian to manage all the check-ins.

**Comment by etosch** [comment]
I think the course webpage says we have a final exam now, so I doubt
there's going to be a next time.

On Sun, Nov 4, 2012 at 4:04 PM, guptha- notifications@github.com wrote:

> Thankfully, it was a minor change. The next time we do something like
> this,
> we should have a Configuration Librarian to manage all the check-ins.
> 
> On Sun, Nov 4, 2012 at 4:02 PM, etosch notifications@github.com wrote:
> 
> > I clicked on my commit to add my changes back into the version I pulled;
> > if
> > yours weren't too integrated, you might be able to do that too? You can
> > click on "raw" to get something easy to copy and paste.
> > 
> > On Sun, Nov 4, 2012 at 3:58 PM, guptha- notifications@github.com
> > wrote:
> > 
> > > I just looked, and my change in vmtest/tests.js has disappeared too.
> > > 
> > > On Sun, Nov 4, 2012 at 3:52 PM, etosch notifications@github.com
> > > wrote:
> > > 
> > > > Mine were in vmtest.js and the index.html. These tests mentioned
> > > > above
> > > > were
> > > > still failing before I added my changes back in. My changes were
> > > > checked
> > > > in
> > > > and working last night and disappeared in the middle of the night.
> > > > 
> > > > On Sun, Nov 4, 2012 at 3:49 PM, guptha- notifications@github.com
> > > > wrote:
> > > > 
> > > > > Which file(s) were your changes in?
> > > > > 
> > > > > On Sun, Nov 4, 2012 at 3:43 PM, etosch notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > these are still failing on my local copy. also, my changes were
> > > > > > overwritten. ive added them back but don't want to push until im
> > > > > > sure
> > > > > > we
> > > > > > have the most recently/accurate code up. what the hell is going
> > > > > > on?
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > > > 
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055130>.
> > > > > 
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055217>.
> > > > 
> > > > ## 
> > > > 
> > > > Emma Tosch
> > > > Graduate Research Assistant, Computational Intelligence Lab,
> > > > Hampshire
> > > > College
> > > > MS/PhD student, University of Massachusetts, Amherst
> > > > etosch@cs.umass.edu
> > > > http://cs.umass.edu/~etosch
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055253>.
> > > 
> > > On Sun, Nov 4, 2012 at 3:52 PM, etosch notifications@github.com
> > > wrote:
> > > 
> > > > Mine were in vmtest.js and the index.html. These tests mentioned
> > > > above
> > > > were
> > > > still failing before I added my changes back in. My changes were
> > > > checked
> > > > in
> > > > and working last night and disappeared in the middle of the night.
> > > > 
> > > > On Sun, Nov 4, 2012 at 3:49 PM, guptha- notifications@github.com
> > > > wrote:
> > > > 
> > > > > Which file(s) were your changes in?
> > > > > 
> > > > > On Sun, Nov 4, 2012 at 3:43 PM, etosch notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > these are still failing on my local copy. also, my changes were
> > > > > > overwritten. ive added them back but don't want to push until im
> > > > > > sure
> > > > > > we
> > > > > > have the most recently/accurate code up. what the hell is going
> > > > > > on?
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > > > 
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055130>.
> > > > > 
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055217>.
> > > > 
> > > > ## 
> > > > 
> > > > Emma Tosch
> > > > Graduate Research Assistant, Computational Intelligence Lab,
> > > > Hampshire
> > > > College
> > > > MS/PhD student, University of Massachusetts, Amherst
> > > > etosch@cs.umass.edu
> > > > http://cs.umass.edu/~etosch
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055253>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055334>.
> > 
> > ## 
> > 
> > Emma Tosch
> > Graduate Research Assistant, Computational Intelligence Lab, Hampshire
> > College
> > MS/PhD student, University of Massachusetts, Amherst
> > etosch@cs.umass.edu
> > http://cs.umass.edu/~etosch
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055380>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055404.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by guptha-** [comment]
Hmmm. I thought we had another project...

**Comment by etosch** [comment]
You and me both, but I also thought there wasn't a final and now that's
there, but there's no project 2 info, which I assumed would be up by now...

On Sun, Nov 4, 2012 at 4:12 PM, guptha- notifications@github.com wrote:

> Hmmm. I thought we had another project...
> 
> On Sun, Nov 4, 2012 at 4:07 PM, etosch notifications@github.com wrote:
> 
> > I think the course webpage says we have a final exam now, so I doubt
> > there's going to be a next time.
> > 
> > On Sun, Nov 4, 2012 at 4:04 PM, guptha- notifications@github.com
> > wrote:
> > 
> > > Thankfully, it was a minor change. The next time we do something like
> > > this,
> > > we should have a Configuration Librarian to manage all the check-ins.
> > > 
> > > On Sun, Nov 4, 2012 at 4:02 PM, etosch notifications@github.com
> > > wrote:
> > > 
> > > > I clicked on my commit to add my changes back into the version I
> > > > pulled;
> > > > if
> > > > yours weren't too integrated, you might be able to do that too? You
> > > > can
> > > > click on "raw" to get something easy to copy and paste.
> > > > 
> > > > On Sun, Nov 4, 2012 at 3:58 PM, guptha- notifications@github.com
> > > > wrote:
> > > > 
> > > > > I just looked, and my change in vmtest/tests.js has disappeared
> > > > > too.
> > > > > 
> > > > > On Sun, Nov 4, 2012 at 3:52 PM, etosch notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > Mine were in vmtest.js and the index.html. These tests mentioned
> > > > > > above
> > > > > > were
> > > > > > still failing before I added my changes back in. My changes were
> > > > > > checked
> > > > > > in
> > > > > > and working last night and disappeared in the middle of the
> > > > > > night.
> > > > > > 
> > > > > > On Sun, Nov 4, 2012 at 3:49 PM, guptha- <
> > > > > > notifications@github.com>
> > > > > 
> > > > > wrote:
> > > > > 
> > > > > > > Which file(s) were your changes in?
> > > > > > > 
> > > > > > > On Sun, Nov 4, 2012 at 3:43 PM, etosch <
> > > > > > > notifications@github.com>
> > > > > > 
> > > > > > wrote:
> > > > > > 
> > > > > > > > these are still failing on my local copy. also, my changes
> > > > > > > > were
> > > > > > > > overwritten. ive added them back but don't want to push
> > > > > > > > until
> > > > > > > > im
> > > > > > > > sure
> > > > > > > > we
> > > > > > > > have the most recently/accurate code up. what the hell is
> > > > > > > > going
> > > > > > > > on?
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub<
> > > > > > > 
> > > > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055130>.
> > > > > > > 
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub<
> > > > > > 
> > > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055217>.
> > > > > > 
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Emma Tosch
> > > > > > Graduate Research Assistant, Computational Intelligence Lab,
> > > > > > Hampshire
> > > > > > College
> > > > > > MS/PhD student, University of Massachusetts, Amherst
> > > > > > etosch@cs.umass.edu
> > > > > > http://cs.umass.edu/~etosch
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > > > 
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055253>.
> > > > > 
> > > > > 
> > > > > On Sun, Nov 4, 2012 at 3:52 PM, etosch notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > Mine were in vmtest.js and the index.html. These tests mentioned
> > > > > > above
> > > > > > were
> > > > > > still failing before I added my changes back in. My changes were
> > > > > > checked
> > > > > > in
> > > > > > and working last night and disappeared in the middle of the
> > > > > > night.
> > > > > > 
> > > > > > On Sun, Nov 4, 2012 at 3:49 PM, guptha- <
> > > > > > notifications@github.com>
> > > > > 
> > > > > wrote:
> > > > > 
> > > > > > > Which file(s) were your changes in?
> > > > > > > 
> > > > > > > On Sun, Nov 4, 2012 at 3:43 PM, etosch <
> > > > > > > notifications@github.com>
> > > > > > 
> > > > > > wrote:
> > > > > > 
> > > > > > > > these are still failing on my local copy. also, my changes
> > > > > > > > were
> > > > > > > > overwritten. ive added them back but don't want to push
> > > > > > > > until
> > > > > > > > im
> > > > > > > > sure
> > > > > > > > we
> > > > > > > > have the most recently/accurate code up. what the hell is
> > > > > > > > going
> > > > > > > > on?
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub<
> > > > > > > 
> > > > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055130>.
> > > > > > > 
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub<
> > > > > > 
> > > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055217>.
> > > > > > 
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Emma Tosch
> > > > > > Graduate Research Assistant, Computational Intelligence Lab,
> > > > > > Hampshire
> > > > > > College
> > > > > > MS/PhD student, University of Massachusetts, Amherst
> > > > > > etosch@cs.umass.edu
> > > > > > http://cs.umass.edu/~etosch
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > > > 
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055253>.
> > > > > 
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055334>.
> > > > 
> > > > ## 
> > > > 
> > > > Emma Tosch
> > > > Graduate Research Assistant, Computational Intelligence Lab,
> > > > Hampshire
> > > > College
> > > > MS/PhD student, University of Massachusetts, Amherst
> > > > etosch@cs.umass.edu
> > > > http://cs.umass.edu/~etosch
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055380>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055404>.
> > 
> > ## 
> > 
> > Emma Tosch
> > Graduate Research Assistant, Computational Intelligence Lab, Hampshire
> > College
> > MS/PhD student, University of Massachusetts, Amherst
> > etosch@cs.umass.edu
> > http://cs.umass.edu/~etosch
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055436>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055492.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by emeryberger** [comment]
Have no fear, there's a second project coming.

## 

Professor Emery Berger
Department of Computer Science
University of Massachusetts, Amherst
www.cs.umass.edu/~emery

**Comment by etosch** [comment]
Be not afraid : second coming project?

On Sun, Nov 4, 2012 at 4:20 PM, Emery Berger notifications@github.comwrote:

> Have no fear, there's a second project coming.
> 
> ## 
> 
> Professor Emery Berger
> Department of Computer Science
> University of Massachusetts, Amherst
> www.cs.umass.edu/~emery
> 
> On Sun, Nov 4, 2012 at 4:17 PM, etosch notifications@github.com wrote:
> 
> > You and me both, but I also thought there wasn't a final and now that's
> > there, but there's no project 2 info, which I assumed would be up by
> > now...
> > 
> > On Sun, Nov 4, 2012 at 4:12 PM, guptha- notifications@github.com
> > wrote:
> > 
> > > Hmmm. I thought we had another project...
> > > 
> > > On Sun, Nov 4, 2012 at 4:07 PM, etosch notifications@github.com
> > > wrote:
> > > 
> > > > I think the course webpage says we have a final exam now, so I doubt
> > > > there's going to be a next time.
> > > > 
> > > > On Sun, Nov 4, 2012 at 4:04 PM, guptha- notifications@github.com
> > > > wrote:
> > > > 
> > > > > Thankfully, it was a minor change. The next time we do something
> > > > > like
> > > > > this,
> > > > > we should have a Configuration Librarian to manage all the
> > > > > check-ins.
> > > > > 
> > > > > On Sun, Nov 4, 2012 at 4:02 PM, etosch notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > I clicked on my commit to add my changes back into the version I
> > > > > > pulled;
> > > > > > if
> > > > > > yours weren't too integrated, you might be able to do that too?
> > > > > > You
> > > > > > can
> > > > > > click on "raw" to get something easy to copy and paste.
> > > > > > 
> > > > > > On Sun, Nov 4, 2012 at 3:58 PM, guptha- <
> > > > > > notifications@github.com>
> > > > > 
> > > > > wrote:
> > > > > 
> > > > > > > I just looked, and my change in vmtest/tests.js has
> > > > > > > disappeared
> > > > > > > too.
> > > > > > > 
> > > > > > > On Sun, Nov 4, 2012 at 3:52 PM, etosch <
> > > > > > > notifications@github.com>
> > > > > > 
> > > > > > wrote:
> > > > > > 
> > > > > > > > Mine were in vmtest.js and the index.html. These tests
> > > > > > > > mentioned
> > > > > > > > above
> > > > > > > > were
> > > > > > > > still failing before I added my changes back in. My changes
> > > > > > > > were
> > > > > > > > checked
> > > > > > > > in
> > > > > > > > and working last night and disappeared in the middle of the
> > > > > > > > night.
> > > > > > > > 
> > > > > > > > On Sun, Nov 4, 2012 at 3:49 PM, guptha- <
> > > > > > > > notifications@github.com>
> > > > > > > 
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > > Which file(s) were your changes in?
> > > > > > > > > 
> > > > > > > > > On Sun, Nov 4, 2012 at 3:43 PM, etosch <
> > > > > > > > > notifications@github.com>
> > > > > > > > 
> > > > > > > > wrote:
> > > > > > > > 
> > > > > > > > > > these are still failing on my local copy. also, my
> > > > > > > > > > changes
> > > > > > > > > > were
> > > > > > > > > > overwritten. ive added them back but don't want to push
> > > > > > > > > > until
> > > > > > > > > > im
> > > > > > > > > > sure
> > > > > > > > > > we
> > > > > > > > > > have the most recently/accurate code up. what the hell
> > > > > > > > > > is
> > > > > > > > > > going
> > > > > > > > > > on?
> > > > > > > > > > 
> > > > > > > > > > —
> > > > > > > > > > Reply to this email directly or view it on GitHub<
> > > > > 
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055130>.
> > > > > 
> > > > > > > > > —
> > > > > > > > > Reply to this email directly or view it on GitHub<
> > > > > > > > 
> > > > > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055217>.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ## 
> > > > > > > > 
> > > > > > > > Emma Tosch
> > > > > > > > Graduate Research Assistant, Computational Intelligence Lab,
> > > > > > > > Hampshire
> > > > > > > > College
> > > > > > > > MS/PhD student, University of Massachusetts, Amherst
> > > > > > > > etosch@cs.umass.edu
> > > > > > > > http://cs.umass.edu/~etosch
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub<
> > > > > > > 
> > > > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055253>.
> > > > > > > 
> > > > > > > 
> > > > > > > On Sun, Nov 4, 2012 at 3:52 PM, etosch <
> > > > > > > notifications@github.com>
> > > > > > 
> > > > > > wrote:
> > > > > > 
> > > > > > > > Mine were in vmtest.js and the index.html. These tests
> > > > > > > > mentioned
> > > > > > > > above
> > > > > > > > were
> > > > > > > > still failing before I added my changes back in. My changes
> > > > > > > > were
> > > > > > > > checked
> > > > > > > > in
> > > > > > > > and working last night and disappeared in the middle of the
> > > > > > > > night.
> > > > > > > > 
> > > > > > > > On Sun, Nov 4, 2012 at 3:49 PM, guptha- <
> > > > > > > > notifications@github.com>
> > > > > > > 
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > > Which file(s) were your changes in?
> > > > > > > > > 
> > > > > > > > > On Sun, Nov 4, 2012 at 3:43 PM, etosch <
> > > > > > > > > notifications@github.com>
> > > > > > > > 
> > > > > > > > wrote:
> > > > > > > > 
> > > > > > > > > > these are still failing on my local copy. also, my
> > > > > > > > > > changes
> > > > > > > > > > were
> > > > > > > > > > overwritten. ive added them back but don't want to push
> > > > > > > > > > until
> > > > > > > > > > im
> > > > > > > > > > sure
> > > > > > > > > > we
> > > > > > > > > > have the most recently/accurate code up. what the hell
> > > > > > > > > > is
> > > > > > > > > > going
> > > > > > > > > > on?
> > > > > > > > > > 
> > > > > > > > > > —
> > > > > > > > > > Reply to this email directly or view it on GitHub<
> > > > > 
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055130>.
> > > > > 
> > > > > > > > > —
> > > > > > > > > Reply to this email directly or view it on GitHub<
> > > > > > > > 
> > > > > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055217>.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ## 
> > > > > > > > 
> > > > > > > > Emma Tosch
> > > > > > > > Graduate Research Assistant, Computational Intelligence Lab,
> > > > > > > > Hampshire
> > > > > > > > College
> > > > > > > > MS/PhD student, University of Massachusetts, Amherst
> > > > > > > > etosch@cs.umass.edu
> > > > > > > > http://cs.umass.edu/~etosch
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub<
> > > > > > > 
> > > > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055253>.
> > > > > > > 
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub<
> > > > > > 
> > > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055334>.
> > > > > > 
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Emma Tosch
> > > > > > Graduate Research Assistant, Computational Intelligence Lab,
> > > > > > Hampshire
> > > > > > College
> > > > > > MS/PhD student, University of Massachusetts, Amherst
> > > > > > etosch@cs.umass.edu
> > > > > > http://cs.umass.edu/~etosch
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > > > 
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055380>.
> > > > > 
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055404>.
> > > > 
> > > > ## 
> > > > 
> > > > Emma Tosch
> > > > Graduate Research Assistant, Computational Intelligence Lab,
> > > > Hampshire
> > > > College
> > > > MS/PhD student, University of Massachusetts, Amherst
> > > > etosch@cs.umass.edu
> > > > http://cs.umass.edu/~etosch
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055436>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055492>.
> > 
> > ## 
> > 
> > Emma Tosch
> > Graduate Research Assistant, Computational Intelligence Lab, Hampshire
> > College
> > MS/PhD student, University of Massachusetts, Amherst
> > etosch@cs.umass.edu
> > http://cs.umass.edu/~etosch
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055543>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/114#issuecomment-10055576.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by emeryberger** [comment]
If Romney wins, then the end times are surely here, so then yes.

Otherwise, just an ordinary non-zombie project.

## 

Professor Emery Berger
Department of Computer Science
University of Massachusetts, Amherst
www.cs.umass.edu/~emery

**Comment by etosch** [comment]
wont fix
