### ISSUE TITLE
constant pool

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#13]
There are separately enumerated and indexed constant pools for references to strings, types, fields, and methods.

**Comment by etosch** [comment]
I just pushed some really simple code. My preliminary questions are:
1) How far do we need to drill down to get the details of the memory? I'm assuming that each entry in the array is one byte and that characters are one byte each. This is find for strings - I'm not sure how it's going to deal with other types. 
2) How to tell what type a constant is - are we going to have annotations? Are we going to use native java facilities?
3) How to access constants? Should we be hashing? I'm not sure how a constant pool is supposed to work. I'm guessing we just want to keep nonmutable things together in one place and will want code elsewhere to point at these things, rather than make copies locally? i.e. what does it mean to have a constant pool?

**Comment by jjfiv** [comment]
The current plan is to resolve all references to constants and the constant pool during load time. The return of the loader will be classes in a list. See mock-hello.js.
