### ISSUE TITLE
resolving virtual methods

### ISSUE THREAD

**Issue by jen4ik** [jjfiv/dalvik-js#14]
So each class has a list of all the virtual methods it contains, which means you need to go up level by level until you find one of its parents that has the method written out specifically.
Do we prefer the result to be space efficient (have a "pointer" to the method's string) or time efficient (copy the method's text into its slot in the array in the current class?)

**Comment by jjfiv** [comment]
The loader will resolve calls to methods to have references to their strings. See src/mock-hello.js

e.g.
{op: "invoke", kind: "virtual", argumentRegisters: [0, 1], method: "Ljava/io/Printstream;.println"}

This kind of work will need to be done for "invoke" "interface" methods, so instances of classes will need a way to maintain their types for the resolution of interface methods from an abstract referene. This will be a new issue.
