### ISSUE TITLE
design needed for class instances

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#16]
Need a type: String, and I'm not sure what else. Will need instance fields, and to call an appropriate constructor. Someone needs to mock up .java files, and dex them, and see what the code looks like. Are calls to the constructor put in explicitly or is that our job on "new"?

**Comment by jen4ik** [comment]
So I have a class and a sub-class written in java, but I had trouble dexing them.
They're in the /test/ClassHierarchyTest folder in Git (related to issue #15)

**Comment by jjfiv** [comment]
Both of these worked for me.
dx --dex --output clh.dex ClassHierarchyTest.jar
dx --dex --output clh.dex ClassHierarchyTest.class ClassHierarchyTest\$Penguin.class 

The format is:
dx --dex --output OUT_FILE_NAME INPUT_FILES

**Comment by jen4ik** [comment]
I closet Issue #15 after successfully dexing and dasming it

From looking at the dasm, looks like this is not going to be pleasant. It doesn't specify in the subClass any of the superClass's methods or members. Haven't looked at the full program through John's disassembler yet, though

**Comment by jen4ik** [comment]
Can we close this one?

**Comment by jjfiv** [comment]
The parts that aren't closed are covered by Issue #52.
