### ISSUE TITLE
load core.odex into our VM

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#19]
I built the standard class libraries as provided by android; there is an accompanying README in case I get hit by a bus and it needs to be redone.

The dex loader will need a lot of work throughout this process, because while working on it I blatantly skipped anything I didn't absolutely need.

It is possible that once this is run, if it takes a long time, we can generate a javascript file with these classes predefined --- i.e. store the output in a file so that we don't actually load/decode this dex file every time. That javascript file will need to be rerun every time the dexLoader or icode changes, I would imagine.

I'm not sure exactly which methods are missing / have a fake implementation, but these will be what we need to implement in javascript.

**Comment by jjfiv** [comment]
core.odex was the incorrect file; core.dex has been located; and loads completely through the dexLoader. icodeGen is incomplete, but all the structures are parsed correctly until that point.

70% complete.

**Comment by etosch** [comment]
So would this be the last thing we test? Could write up some things we need to test on the wiki?

**Comment by jjfiv** [comment]
This cannot be the last thing we test; we need to be able to load this to run any remotely real-world sample programs. I will work on defining our test suite.

**Comment by jen4ik** [comment]
The file finishes loading
Put an exception:
Uncaught Exception: Proxy already loaded

**Comment by jjfiv** [comment]
I think we will target loading only a portion of this file, it has 1044 native methods... Proxy error will go away.
