### ISSUE TITLE
Dalvik opcodes to icode conversion

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#20]
In the dexLoader module, most likely.

This conversion needs to be done to convert the dalvik opcodes to our more compact "icode" --- this translation step will make executing instructions simpler; the VM will be able to step to the next entry in the icode array, rather than have to figure out how long the instruction is. In a sense, we're converting CISC to RISC.

Unfortunately, the address offsets in `packed-switch`, `sparse-switch`, `goto`, `goto/16`, and `goto/32` will be in terms of the original bytecode. The same is true for the try-catch data at the end of the method definition. This will be also true in terms of every single `if-*` variant.

Therefore, in the routine for translating into icode, the algorithm will need to maintain a table; with one entry for each new icode statement generated, indicating it's original bytecode offset. To cope with forward jumps, this array might need to be built in advance. Then, when an address is encountered, a linear search through the address translation array should provide the new icode address that our interpreter will need.

**Comment by jjfiv** [comment]
This will happen in "icodeGen.js".

This is what Emma and I discussed as the CISC->RISC conversion for internal execution.

**Comment by etosch** [comment]
So at the bottom of icodeGen.js, we pop out the RISC version of these, right? Then icodeExecute.js is attached to the VM?

**Comment by jjfiv** [comment]
`icodeExecute` is used by the VM.

**Comment by etosch** [comment]
John - can you take a look at the code I just pushed? The major changes I just made were regarding the CISC->RISC conversion:

1) I added `setRegisterWide` and `getRegisterWide` in [Thread.js](https://github.com/jjfiv/dalvik-js/blob/master/src/Thread.js#L69).
2) I started implementing family codes. Family codes are produced by calling `inc()`, which gives the next family code. Family codes are saved in a variable that is used in icodeExecute.js to look up the implementation.
3) The following data structures are used: 
- `opName` hashes the Dalvik opcode name according to its numeric opcode. This should only be used for debugging and we should remove it before we turn in our final code.
- `iCode` maps the family icode, which is what we will be using as "op" in our RISC implementation, to the Dalvik opcode. This has the same size as the total number of Dalvik opcodes right now, for ease of lookup with opcode names. Once we have the RISC arch. established, we can go back and prune.
- `icodeAddrSize` tracks the address size, which will be used in the `icodeGen` function to figure out which `get*` to use from `dexLoader`.

*`icodeRegSize` tracks whether we're moving to a regular sized register or to a wide register.

4) RISC instructions are produced in the `icodeGen` function, which fills out a structure containing an icode, an offset, the parsed args, and the register size (32 or 62).

5) Using the RISC instructions, execution is controlled by family opcode. See [icodeExecute](https://github.com/jjfiv/dalvik-js/blob/master/src/icodeExecute.js) for more details.

**Comment by jjfiv** [comment]
Some initial thoughts:
-  Please review `icode.xls`. I put a lot of time and thought into where to break up opcodes, and some of my comments are based on knowledge present in there. It may need changes or updates, I realize, but we can create issues as we find them.
- You're now using indexed arguments, which means we have to look at a spec, and know where things come from. I named the arguments in `icode.xls` so that it would be obvious what each piece does, and the VM wouldn't have to know anything about dalvik bytecode. Indexes leak, and will make the number of families we need larger.
- I really don't like using numbers for opcode families; there's no need to be efficient like that. If Javascript had enums, then I'd be for it. Let's use the strings defined in `icode.xls`. That way they won't change if we add a new family, and they are automatically human-readable. If we `console.log` a command that's not working, and it tells me that it's family 4, someone's going to have to go count `inc()` statements, and that won't be fun.
- `getRegisterWide` and `setRegisterWide` can now be updated to use `gLong` objects.
- `move-exception` needs to be its own family, because it's a different kind of special register.
- the register widths will always be either 32 or 64, which is why I was representing them with `wide=true`. The only exception, I believe, is the casting `int-to-long` and `long-to-int` kind of opcodes. See icode `primitive-cast`
- I don't think parser will extend well to `invoke-direct` (`iCodeArgSize=[4,12,N]`) or other arguments like `*-switch`, which is why I was doing the one function per family rather than a data driven approach. I think the idea can totally work, but since there are a lot of oddball opcodes, it needs to be a level down rather than directly in icodeGen, so that we can still special case what we need without writing a different loop body.
- minor detail: Either we capitalize everything `icode` or everything `iCode`. I don't particularly care which, but we should be consistent.
- Your "Vanilla Binary" family is too broad. The floating point opcodes are not binary based. We need to break things down into smaller parts.
- I think `_actionMap` would be better presented as if-statements for legibility; there aren't enough cases, and we should assert on that kind of error, rather than throwing an exception; it's not the kind of thing to recover from for now. Eventually, we could throw a an error that indicates we stop trying to run all threads or something, but that would have to be caught at the VM level.
- `move-result` and family are moved from a special "result" register that is set by the `return` opcodes. There is a field called `Thread.prototype._result` and a `Thread.prototype.setResult`

**Comment by etosch** [comment]
I'll hit the xls file as I expand and revise.

I'll note what you're saying about indexing, but unless there's a serious issue in JS that I don't know about, it isn't a compelling enough argument for me to change it. If it becomes an issue, I'll change then. Also, I'm not following what you're saying about needing more families.

As for numbers of opcode families, I am currently keeping the opName, as well as the assigned values. I could keep the vars for the assigned values in an array as well and include this as a debug option, since I can always write a function to resolve the lookup. 

I'll create issues to update the wide instructions.

I'll also create an issue to differentiate move-exception.

I'll create an issue for how to deal with the weird codes with the offset issues in the parser. I take it that the gist of this is that it will require modifying the parser. Do you want to take that task on then?

I'll create another issue for making the icode thing consistent.

regarding vanilla binary - it was 2am, I was tired. Will update the source code and the issue later, after machine learning and post-consulting the xls file.

mmmmm...I find the actionMap approach easier to read. I started with if-statements, but switched over to this. as for assert vs throwing exceptions...meh, I'll think about it.

I'll create an issue for the result regs.

**Comment by jjfiv** [comment]
I see now that you're assigning `inc();` to a variable, except in the NOP case. In that case I'm less concerned, but I still feel like using integers is optimizing something that doesn't yet work.

The plain old array for arguments is not going to be fun to debug or write VM code. It's making Javascript even less typed than it is. I realize that it is a lot more work to name arguments. But we're either naming them here or we're naming them when we use them. I would rather do it here. Then it gets put into an intermediate representation that we can look at. We get errors if we look for a "dest" on an opcode that doesn't have one. No errors if we misinterpret the nth element of something.

icode:
`setRegister(op.dest, getRegister(op.src));`

currently checked in code:
`setRegister(op.args[0], getRegister(op.args[1]));`

**Comment by jjfiv** [comment]
Separate icode has moved to branch [different-icode](https://github.com/jjfiv/dalvik-js/tree/different-icode). `icodeGen.js` development will continue on master generating icodes in the style of `icode.xls` and `mock-hello.js`

**Comment by jjfiv** [comment]
There is a thoroughly tested `AddressTranslator` step, and `icodeGen.js` only lacks support for three opcodes. These will be tracked separately.
