### ISSUE TITLE
dex loader must output equivalent of mock-hello.js data structures

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#21]
Then we will be done with this one

**Comment by etosch** [comment]
Push dexLoader, please?

**Comment by jjfiv** [comment]
I've pushed it; need to implement "invoke-virtual" inside of "icodeGen.js" and this will be 99% done. If icodeGen is completely opaque, we can talk about it.

**Comment by etosch** [comment]
Would this be an appropriate next step? I've assigned it to myself in #43. If so, could you tag that with the next steps label?
