### ISSUE TITLE
javascript binary <-> double/float conversions

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#22]
Seems like the best way of doing this (consulted google briefly) is with [Typed Arrays](https://developer.mozilla.org/en/JavaScript_typed_arrays). So we would write it to a byte array, cast it to a float array and do it like that. This would depend on such array support ( we already do by depending on the FileAPI, I believe )

**Comment by etosch** [comment]
Is this for opcodes (e.g. the ones later in the list) or for handling some data issue with Javascript? Also, could you tag this issue with whatever appropriate part of the process this belongs to (make up a new one if you need to).

**Comment by jjfiv** [comment]
This is for inside of the static data parser of the Dex Loader. [dexLoader.js:368](https://github.com/jjfiv/dalvik-js/blob/master/src/dexLoader.js#L368) (If that line moves, look for `ValueType.Float` and `ValueType.Double`)

Basically, we need some way of reading binary float and double literals into appropriate javascript objects.

**Comment by guptha-** [comment]
Correct me if I am wrong: the input will be the 32-bits of the bytecode in hex and the output should be the actual float. For example, if the input is 0x40000000, the output will be 2.0.

**Comment by jjfiv** [comment]
Correct (I have no idea if your particular example is correct)
We also need a method for 64-bit things.

**Comment by guptha-** [comment]
OK. 64-bit is a bit more complicated, but we can extend the same logic with some modifications. I am focusing on 32-bit now and when that's done, I will extend it to 64-bit.

I am looking at having a higher word and a lower word while dealing with 64-bit.

**Comment by jjfiv** [comment]
Check out `src/gLong.js` it's from Google's libraries, and gives math and other operations on two 32-bit pieces. The implementation can easily be two separate routines. We'll always know which one we need to call.

**Comment by guptha-** [comment]
floatFromByteCode is done and checked in. Someone will have to unit test independently. I have added a few asserts to check functionality.

double is still pending.

**Comment by guptha-** [comment]
Double is done and checked in too. The issue can be closed after someone else unit tests.

**Comment by jjfiv** [comment]
Looks really good, @guptha-. I think I will close this and we can open new issues as they appear.
