### ISSUE TITLE
Upload.js - needs to know what to do when files are ready

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#24]
From Upload.js

// TODO have a protocol for setting this callback
Upload.prototype.onFileReady = function(fileName, fileData) {
  var dex = new DEXData(new ArrayFile(fileData));
};

**Comment by jjfiv** [comment]
Upload controls all the HTML needed for file upload; the process of callbacks. So, we need some sort of callback here that does something when the file is loaded.

Right now, it creates a DEXData object. At some point, the data loaded in needs to get to the VM; for now that part of the design isn't connected. We either code directly, or we make the Upload class take a callback that tells it what to do with the data when it loads. That was what I mean by "protocol for setting this callback".

In the interest of simplicity, we can skip the callback part and call directly into a VM.defineMoreClasses or something, but then VM has to be global. So. this is really about solving the dependencies; pretty simple task, but I think one that we need to do slightly later.

**Comment by etosch** [comment]
Okay; how difficult do you think throwing together the hacky (non callback) version? That's what we would need to push through the pipeline, right? Can you write up whatever one would need to know to do this and assign to me or Jennie?

**Comment by jjfiv** [comment]
Right now,

`Upload.js` creates a global `upload` object. This is not correct.
`upload` should be a member of the `VM` class.

An `Upload` object should take as a parameter to its constructor a callback function. This will be given to it by VM.

pseudocode of callback:

```
on file(f):
  classes = parse_dex(f)
  vm.defineClasses(classes)
```

This issue depends on #51

**Comment by jjfiv** [comment]
Looks good. As of recent commits, dex files is loaded, and can be chosen and run from index.html
