### ISSUE TITLE
handling files to upload

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#26]
Currently the load file button for Upload.js only uploads one file at a time. The current implementation keeps an array of chosen files, but in practice only allows one choice Update this to handle:

(1) manually entering more than one dex file sequentially. 
(2) entering more than one file at a time using the file selector. (If I try to load two files at once by selecting two, only the last one is parsed.)
(3) uploading a directory of dex files.

Some other options to consider in the future:
(4) Uploading a zipped file
(5) Uploading a jar
(6) Uploading only the relevant starting point and dynamically loading the necessary dependencies as we go.

**Comment by etosch** [comment]
If you could write/make some test cases to make sure that these options work, that would be great. Be sure to document them in the wiki.

**Comment by jjfiv** [comment]
Future options (4) and (5) would require a zip library written in Javascript. Also, people generally don't jar or zip dex files.
Future option (6) would require some sort of server. Javascript is restricted from loading things from a user's computer that aren't specified through an `<input type="file" />`

I don't think the rest will be able to be automated tests, unfortunately; unless someone has a really scriptable browser.

**Comment by jjfiv** [comment]
> (2) entering more than one file at a time using the file selector. (If I try to load two files at once by selecting two, only the last one is parsed.)

What browser are you using? I am unable to reproduce this in Firefox 15 and Chromium 20.

There is a bug in the printing of which file gets loaded, but separate, correct DexData is created for the two dex files I used. (See Issue #57 I just assigned to you).

**Comment by jjfiv** [comment]
Is this resolved along with #80?

**Comment by etosch** [comment]
Yup. closing now.
