### ISSUE TITLE
dexing more complicated classes

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#27]
How does the dex tool work? Does the dex tool produce a single dex file that pulls in all dependencies or does it call other dex files? Write a simple java file (e.g. a  "Hello, Team!" file that prints out team member names) that pulls the team member names from another class that contains only fields or a linked list or something.

Add an explanation of how loading local imported classes works in https://github.com/jjfiv/dalvik-js/wiki/Dexify.

**Comment by jjfiv** [comment]
@etosch

Dex files contain 1 to N classes. If you give it a `.jar` or multiple `.class` files, they all become one DEX file.

`dx --dex --output HelloTeam.dex HelloTeam.class TeamNames.class`

HelloTeam.dex now contains: [`class HelloTeam`, `class TeamNames`]

**Comment by etosch** [comment]
Note that this issue is still open - we will need a description to put in the wiki, which will eventually go into our writeup, under the features our system can handle.

**Comment by jen4ik** [comment]
So should I upload the output of the sample file to the wiki, or is something else expected?

**Comment by jjfiv** [comment]
Check in the java files too. We need to start building up our test infrastructure.

**Comment by jen4ik** [comment]
Everything is in Git in a folder: sandbox/ClassHierarchyTest

**Comment by jen4ik** [comment]
Created, dexed, disassembled

teamMember is a class file that has 2 members: String _name, boolean_knowsJS, and a method toString()
vmTeam only has a main method that creates and array of teamMembers, assigns a name to each, and changes the boolean to 2 of them
Then, loops through the array and prints each of them out

Can be found under Sanbox/dalvikTeam

Note that if it's defined under a packages that isn't a default package dex-ing doesn't work with the simple commands
