### ISSUE TITLE
grep trick

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#28]
What's the grep trick you showed me the other day to search through all the contents of the files in a directory that avoided writing

for f in src/*
do
    line=`grep Uint $f`
    if [[ -n $line ]]
          then
          echo "$f : $line"
    fi
done

Also, as you can probably tell, I was trying to figure out where Uint8Array came from. I couldn't find it, so I didn't add it to the dependencies. I want to add this to [useful command line operations](https://github.com/jjfiv/dalvik-js/wiki/cmd).

**Comment by jjfiv** [comment]
[Uint8Array](https://developer.mozilla.org/en-US/docs/JavaScript_typed_arrays/Uint8Array) is an intrinsic --- built into the browser. I discovered it while researching the [File API](http://www.w3.org/TR/FileAPI/)

My favorite grep command is:
`grep Uint * -RIn --color=always`

`-R` recursively searches for files based on the initial set `*`
`-I` ignores any binary files it finds; searching only text files
`-n` causes results to be in the format `file:lineNumber: lineText`
`--color=always` highlights the search text

Filtering with grep:
`grep hello * -RIn | grep -v world`
This finds all files recursively that contain hello but not world.

Other fun args:
`-i` ignore case (lots slower, but sometimes needed)

**Comment by emeryberger** [comment]
You could do this -- recursive search starting from src/, matching every file:

% find src/ -name '*' | xargs grep Uint

-- emery

## 

Professor Emery Berger
Dept. of Computer Science
University of Massachusetts, Amherst
www.cs.umass.edu/~emery

**Comment by emeryberger** [comment]
Nice grep hackery!

## 

Professor Emery Berger
Dept. of Computer Science
University of Massachusetts, Amherst
www.cs.umass.edu/~emery

**Comment by etosch** [comment]
Okay, next grep challenge: how to search for things with spaces? I tried:

grep firstpart\ secondpart ...
grep 'firstpart secondpart' ...
grep "firstpart secondpart" ...

I also tried 

echo "firstpart secondpart" | grep ...

but I didn't know how to make the pipe insert this as the first arg.

**Comment by jjfiv** [comment]
`grep "first second" *` works for me

As does the Regex version:
`grep "first\s\+second" *`

`\s` should match generic whitespace
`\s\+` should match one or more characters of whitespace

Trial and error told me I needed to escape the +; I haven't done too 
much with Regexes in general.

It is possible that the OSX grep is a bit different. `ls`, for example 
has different arguments, if I remember correctly. `man grep` might be 
your friend here.

As far as echoing something to use as the pattern for grep, I don't know 
if that's really possible.

`echo "something" * | xargs grep`

This works, but probably doesn't get what you want? I don't know.
