### ISSUE TITLE
What's up with line 60 in icodeGen?

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#30]
See hanging assignment: https://github.com/jjfiv/dalvik-js/blob/master/src/icodeGen.js#L60

**Comment by jjfiv** [comment]
This is completely a typo, that Javascript let me get away with. My 
apologies.

I was mid thought process, about to take `opArgs[0x0f]`, 
`opArgs[0x10]`, and `opArgs[0x11]` and make them one function; the 
unfinished `dest8`. I don't know why I lost track of that.
