### ISSUE TITLE
parse control commands

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#37]
Implement control commands starting [here](https://github.com/jjfiv/dalvik-js/blob/master/src/icodeGen.js#L122). See #45 for more details.

**Comment by jen4ik** [comment]
first attempt at opCodes conversion pushed to gitHub

**Comment by jen4ik** [comment]
Revisit switch commands after "sparse-switch-table" is figured out

**Comment by jjfiv** [comment]
Implemented, closed for now; bugs can be new issues based on end-to-end tests.
