### ISSUE TITLE
Implement registers/frames

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#4]
"The VM is register-based, and frames are fixed in size upon creation. Each frame consists of a particular number of registers (specified by the method) as well as any adjunct data needed to execute the method, such as (but not limited to) the program counter and a reference to the .dex file that contains the method."

Determine number of registers needed for a given method (this is listed as a property in the dasm file - can we just parse this out?). 

Implement registers as...a map? Should this be in a separate file? Class? Should we have something that produces registers on demand? For example, do we have something like a gensym that produces handles to registers? Do we have a pool of registers of unknown size such that for a given frame, we grab registers as needed?

As for the program counter - do we need two registers for this (global and local)?

"The N arguments to a method land in the last N registers of the method's invocation frame, in order. Wide arguments consume two registers. Instance methods are passed a this reference as their first argument."

**Comment by jjfiv** [comment]
We need to look into and integrate the google long library. Whenever an opcode is "wide" then accessing register N means to grab register N and register N+1 and manipulate it like that. We'll need to create a long object, do the operation(s) and then break it up and put it back into registers. If the google API isn't simple enough we can write our own.
