### ISSUE TITLE
bytecode to icode address conversion

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#50]
This is a  more complicated issue. It has two parts but can't really be separated.
- `goto` `switch` and `if` (and anything else with an address), must be converted from bytecode addresses to icode addresses. This will be a step after the initial translation, because otherwise, we cannot resolve forward branches.
  - An array of offsets should be maintained. For example, the offsets might be [0,3,7,8,9,11] -- this would represent the bytecode address of the icode instruction at that index. Therefore, when resolving a goto, you find out it's source address (looking in that array) and then add the relative offset, and then look through the array for a destination address.
  - Note that bytecode addresses might be in terms of bytes or they might be in terms of "code units" which are 2 bytes long. The documentation is unclear.
- The try/catch and throw information within `dexLoader.js` will need to be translated in a similar fashion. It would make sense to have `icodeGen.js` return the translation array as part of its return value.

**Comment by etosch** [comment]
Is this in relation to #37? (If so, please link to or comment on existing issues in the future, so we don't have wade through additional stuff)

**Comment by jjfiv** [comment]
Yes and no. I think it should be kept separate, although it could be done as part of that issue. I'm trying to generate more standalone chunks. It will depend on that issue being done.
