### ISSUE TITLE
Improvements to Class objects & createInstance

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#52]
Right now the structure defined in [Class.js](https://github.com/jjfiv/dalvik-js/blob/master/src/Class.js) is not very detailed.
- Convert the appropriate pieces of dexLoader to use this type.
- Support a `findMethodBySignature`
  - This will have to take a string of the form `println(I)V`, `multiplyLongs(L,L)L` and return the appropriate method, if any.
  - it will be the responsibility of the calling module to go look for a native method if this returns null
- `createInstance` this will need to walk over the instance fields and create an object with them. This will yield a not-yet complete object that may still need its constructor run. That will be the responsibility of the `new-instance` opcode itself. The resulting `Instance` object must have a `type` field.

**Comment by jjfiv** [comment]
Makes more sense to have it take a `MethodSignature` object than a String of a certain format. See Issue #54

**Comment by jjfiv** [comment]
The best way to do this will be to create some sort of java file, make it into a dex, and try it for various fake classes with various kinds of fields.

**Comment by etosch** [comment]
I'm assigning this to myself, since it ought to be a fairly easy extension beyond what I've already done with `ClassLibrary`. 

Opinions?

**Comment by jjfiv** [comment]
Perfectly fine so long as you have time alongside your midterm to work on it.
