### ISSUE TITLE
clarification on move-wide

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#53]
04 12x  move-wide vA, vB    A: destination register pair (4 bits)
B: source register pair (4 bits)    Move the contents of one register-pair to another.
Note: It is legal to move from vN to either vN-1 or vN+1, so implementations must arrange for both halves of a register pair to be read before anything is written.

The spec here is almost identical to the vanilla move (sans the "Note) - so is the "move-wide" idea here that we're really allocating two adjacent registers by sliding some data over to the adjacent one?

**Comment by etosch** [comment]
Or are we to read this where for vanilla move, the 4-bit register address points to a single block, but for the move-wide, the 4-bit register address points to two adjacent blocks? Given what's stated in the note, it looks like that address could be either the second half or the first half of the two block address - should we have the convention that it always reads from the first half?

**Comment by etosch** [comment]
Finally, if the 4 bits refer to the address of the register, then we have 16 registers...but wait, we have infinite registers. So is this what the move/from16, etc is capturing, i.e. that our "infinite" registers really mean that we have 65,000 or so registers that appear infinite because we'll never use than many, unless we have some really terrible implementation?

**Comment by etosch** [comment]
So we have two "sizes" to think about - the size of address we're reading, and the actual size of the contents we're moving. So:

For the vanilla move, we're moving from a register that's addressed using 4 bits whose contents are of size 32 bits to another register that's addressed using 4 bits and whose contents are of size 32 bits. 

For move-wide, we're moving from a register that's addressed using 4 bits whose contents are of size 64 bits and moving to a register whose address is indicated using 4 bits, but whose contents are of size 64 bits. 

For move/from16, we're moving from a register that's addressed using 16 bits that is of size 32 bits and moving to a register that's addressed using 4 bits that is of size 64.

Why not have all addresses of maximum size? Must be due to space considerations. Is this the sort of thing that dexification optimizes for? i.e. does the register address size really matter that much to us in the internal representation, since we're addressing using local variable names anyway? Does it only matter for parsing?

**Comment by jjfiv** [comment]
- There are 2^16 registers available per function. Most opcodes only address the first 2^4 registers. They don't have all addresses at maximum size to save space; 99% of the time, they only need the first sixteen registers, so it doesn't make sense to address all of them all the time; it would just be storing a bunch of extra zeroes.
- Once we get to icode, the size of the register id doesn't matter anymore. (part of the point of icode)

**Comment by etosch** [comment]
Awesome. In that case, I have some ideas about refactoring for RISC.

Also, for things like the difference between "move" and "move-object:" these look the same, except are we to assume that "move" can move anything, whereas "move-object" can only move object types? Does this matter for our RISC spec/VM?

**Comment by jjfiv** [comment]
Implementation-wise, they'll be the same. I was tentatively keeping it in so that we could self-test that move-object commands were only used on object types, but it really doesn't matter. There doesn't seem to be any exception to be thrown on a bad move command. Honestly, I'm not really sure why they're separate opcodes at all.

**Comment by etosch** [comment]
Maybe it's for the internal generation of the opcodes? Like, maybe the dex tool uses some annotations?

**Comment by jjfiv** [comment]
Confirmed in dalvik source; they share an implementation. I think maybe they use it for debugging; to know how to interpret the registers at step time?

Contents of `vm/mterp/c/MOVE_OBJECT.cpp`: `%include "c/MOVE.cpp"`

I will remove `move-object` if it exists in `icode.xls`

**Comment by jjfiv** [comment]
We're going to attempt (as long as possible) to store adjacent "wide" chunks in a single register (ie. a glong in register 1 instead of half in reg 1 and half in reg 2)
