### ISSUE TITLE
Build a MethodSignature class

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#54]
This class will contain
- name of the method `print`
- return value `new Type("V")`
- parameter types `[ new Type("I"); ]`

It will have a method
`MethodSignature.prototype.equals(other: MethodSignature)`

This will allow classes to implement their method `Class.prototype.findMethod(s: MethodSignature)`

**Comment by jjfiv** [comment]
Assign to @jen4ik: This will be one of the major clients of your `Type` class.

**Comment by jjfiv** [comment]
assume `MethodSignature = function(name: String, returnType: Type, parameterTypes: Array<Type>) { ... }`
for now, it may decode a string later.

`print(TypeA,TypeB,TypeC)ReturnType`

**Comment by jen4ik** [comment]
Can I add this to the Method.js file or should it be in a separate file?

**Comment by jjfiv** [comment]
Make a separate file; they're cheap; makes it easier to find.

**Comment by jen4ik** [comment]
I'm assuming that both returnType<Type> and parameterTypes<Type> are what the Type.js file spits out? Or is it low level code from the disassembler?

**Comment by jjfiv** [comment]
Right, they're your `Type` objects. Once this is ready, there'll be 
some work to go back into dexloader and make sure it's outputting real 
`Type` objects and `MethodSignature` objects.

**Comment by jen4ik** [comment]
So when you call MethodSignature, do you pass "thing._type" or just "thing" and I should use "thing._type" inside the MethSig class?

**Comment by jjfiv** [comment]
You pass just the Type object, and `_type` should be private; if you 
need some information, then that needs to become a method of Type.

**Comment by jen4ik** [comment]
initial write up has been synched
currently has: getName, getReturnType, equals, toStr
Anything else we want to add to that?

(No asserts yet, will leave it for after the midterm)

**Comment by jjfiv** [comment]
Looks good so far. We can add things as they come up.
Thanks,
John

**Comment by jen4ik** [comment]
Was reviewed, closing

**Comment by jjfiv** [comment]
Type objects internally...

**Comment by jen4ik** [comment]
I changed the code before closing this issue
MethodSignature._returnType = returnType;
MethodSignature._parameterTypes.push(parameterTypes[i]);

toStr: _name(parameterTypes[i].getType())_returnType.getType();

Not good enough?

**Comment by jjfiv** [comment]
Never mind, I apologize. I didn't see the commit.

Put at least one `assert` in that file, and then you're done :)

**Comment by jen4ik** [comment]
added getParameterAmount()
added 2 asserts: toStr(), _parameterAmount
