### ISSUE TITLE
Extract dex files from apk

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#55]
An APK is an Android Zip file. This is lower priority, but something that needs to be considered.

**Comment by jjfiv** [comment]
Possible Zip Library - [Zip.js](http://gildas-lormeau.github.com/zip.js/)

**Comment by emeryberger** [comment]
You should talk to the Doppio folks about zip stuff.

On Oct 16, 2012, at 12:05 PM, John Foley notifications@github.com wrote:

Possible Zip Library - Zip.js http://gildas-lormeau.github.com/zip.js/

—
Reply to this email directly or view it on
GitHubhttps://github.com/jjfiv/dalvik-js/issues/55#issuecomment-9502552.

**Comment by jjfiv** [comment]
The Doppio folks use a `java.util.zip` from [JazzLib](http://jazzlib.sourceforge.net)

This is two issues:
- I don't know if the Android `java.util.zip` is pure java or not. If it isn't, we can look into patching the dex file with JazzLib.
- If we support uploading apk files, we need to unzip them to find the dex files. For that we would probably need a Javascript library, unless we invoke our own VM to do it.
