### ISSUE TITLE
recursion and move-result investigation

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#56]
@guptha- brought up a point about having only one result "register" per thread.

Create a java class with a recursive function and disassemble the dex; Make sure that only one result will be needed at once.

If not, look into StackFrame and Thread and decide how best to proceed.

Keep your class around, too. We ought to have a recursive test for our own sake.

**Comment by jjfiv** [comment]
May be blocked by #99 but I don't want to lose sight of it.

**Comment by guptha-** [comment]
The result is moved to another register immediately after the recursive call. Our factorial program works, which is a great indicator that everything is perfect.

The spec also emphasizes moving out the result to another register immediately after executing any op-code that modifies the result register and dx seems to do the same.

I think we are OK. @jjfiv, do you want me to try out something specific?

**Comment by jjfiv** [comment]
@guptha- checked in a test earlier, so this is done
