### ISSUE TITLE
Convert Type.js to use RegisterValue

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#63]
Not a huge priority, but instead of `return { type: this, value: blah }` we should `return new RegisterValue(this, blah);`

Note I fixed line endings in `Type.js` (I don't know how they got mixed), but make sure you sync before you start working.

**Comment by jen4ik** [comment]
Should I use new Register only for the primitives or for the array and class as well?

**Comment by jjfiv** [comment]
Everything :)

**Comment by jen4ik** [comment]
So for array, the value is [], and for class it's {}?
(Still not a 100% with JS syntax and such?)

**Comment by jjfiv** [comment]
Array is definitely right, class is good enough for now.

**Comment by jen4ik** [comment]
But what should the "This" part be for the array?

**Comment by jjfiv** [comment]
The type itself. The only thing part that changes is the value; all of 
them will be a RegisterValue with a type of "this", we want that 
information.

**Comment by jen4ik** [comment]
Pushed updates
Not certain about correctness

**Comment by jjfiv** [comment]
Looks good.

Small points:
- need to `assert(false, "")`; you're missing a parameter at [Type.js:111](https://github.com/jjfiv/dalvik-js/blob/28bba4784a437a23f7bf0391656fb53740f4e203/src/Type.js#L111)
- could combine most primitive cases, not so important

**Comment by jen4ik** [comment]
Both implemented
Good to close?

**Comment by jjfiv** [comment]
Looks good to me.
