### ISSUE TITLE
64 bit consts

### ISSUE THREAD

**Issue by jen4ik** [jjfiv/dalvik-js#64]
opCodes 0x16, 0x17, 0x18 and 0x19 take a 64 bit value and put it in a register.
Do we have something to pull such large values?
Do we want a get64() function or just use get32 twice?

**Comment by jjfiv** [comment]
Either way. If you want to make an ArrayFile.prototype.get64, it will 
probably call get32 twice inside, and then pass it to a gLong... I don't 
know what the method is called to make a gLong from two 32-bit pieces, 
but I'm sure there is one.

**Comment by jen4ik** [comment]
OK
I just pushed an update to gitHub, can you take a look and see if it makes sense? 0x18, 0x19

**Comment by jen4ik** [comment]
finished
