### ISSUE TITLE
primitives to implement

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#7]
1) bool
2) byte
3) short
4) char
5) int
6) long
7) float
8) double
9) void
10) class

**Comment by etosch** [comment]
Update on the status of this and whether it's still meaningful?

**Comment by jjfiv** [comment]
This is a meaningful checklist in terms of the Type class. I'll let Jennie close it when she's ready.

**Comment by jen4ik** [comment]
this.isPrimitive() return true if this._type is any of V,Z,B,S,C,I,J,F,D
Returns false otherwise 

Is that it, or should there be something else in this?

**Comment by jjfiv** [comment]
`defaultJSObject` should do something for each one.

**Comment by jen4ik** [comment]
I saw that defaulJSObject returns [] for arrays and {} for classes.
What should be returned for a primitive other than its base type?

**Comment by jjfiv** [comment]
Most of them will be zero, or false. gLong will be mildly special.
Not a huge deal, but might make the primitive casting operations easier...

**Comment by jen4ik** [comment]
So in this link it says that JS only has 3 type of primitives: string, numeric, boolean
Should there really be a distinction between ints of sorts / long / floats of sorts?
http://oreilly.com/javascript/excerpts/learning-javascript/javascript-datatypes-variables.html

**Comment by jjfiv** [comment]
Since the integers only hold 32 bits, longs are stolen from the google 
Long library (see gLong.js); the rest of the primitives will need to be 
cut down to size as necessary, basically pretending they're too small to 
hold more, rather than actually being too small.

**Comment by jen4ik** [comment]
I added the things we talked about this morning, but I'm not sure I understood it correctly :\

**Comment by jjfiv** [comment]
Good. Let's be done with this task.
