### ISSUE TITLE
high level overview diagram

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#75]
Per your suggestion.

**Comment by jen4ik** [comment]
https://www.gliffy.com/gliffy/#d=4031670&t=class_diagram

**Comment by etosch** [comment]
When I click on the above link, I'm sent to an exterior website requesting
a login...

On Sat, Nov 3, 2012 at 4:32 PM, jen4ik notifications@github.com wrote:

> https://www.gliffy.com/gliffy/#d=4031670&t=class_diagram
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/75#issuecomment-10043886.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by jen4ik** [comment]
Sent you an invite, it might work
The diagram is too large to fit in a single screen and be readable, so I can't take a snapshot

**Comment by jen4ik** [comment]
screenshots are here:
https://github.com/jjfiv/dalvik-js/blob/master/docs/class_diagram_execution.png
https://github.com/jjfiv/dalvik-js/blob/master/docs/class_diagram_loading.png
https://github.com/jjfiv/dalvik-js/blob/master/docs/class_diagram_objects.png
