### ISSUE TITLE
MethodSignature.prototype.isMain needs to be more specific

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#78]
Right now it just compares names, but in java a `main(V)V` is not a valid entry point.
We need to check the return type and the parameter types.

**Comment by jen4ik** [comment]
Why would it return "this._name" and not true or false?

**Comment by jen4ik** [comment]
Or was it just a stub and it's a very silly question? (:

**Comment by etosch** [comment]
Are you sure you're looking at the right method? `MethodSignature::isMain` returns a boolean; `MethodSignature::getName` is immediately below it and returns this._name

**Comment by jjfiv** [comment]
Update: making this more type specific has created some problems in vmtest; Jennie is looking into it.
