### ISSUE TITLE
implement exceptions/try/catch?

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#8]

**Comment by jjfiv** [comment]
Yes. This is needed. It's a huge part of the format and a bunch of instructions beside. Not to mention Java people use it regularly.

Parsing it out isn't a huge challenge. The challenge is possibly in the implementation of the "throw" opcode. It will have to consult a table based on the type of the object being thrown and try to match it. Unlike C/C++, there is no unwinding of the stack, anything thrown in a method should be caught there? --- IS THIS TRUE?

Need test case and disassembly to be sure.

**Comment by jjfiv** [comment]
This is currently parsed out into the structures inside `TryRange.js`, but that needs to be used on execution. I think the current design would be to have the `throw` opcode tell the thread it's throwing an exception and have the thread handle it.

**Comment by guptha-** [comment]
I have added a test case called tryCatch in the sample directory. Main calls a function "test" inside a try block and has a corresponding catch block for an ArithmeticException. "test" just does a divide by 0. There is no try/catch inside test.

So, in the dexdump, there is no catch for test, but only for main. So, at first glance, it does not look like "test" has inherited the catch blocks from main. However, the VM could easily do the unwinding by itself.

If anyone wants to modify tryCatch.java, just run ./scr afterwards. This will generate the dump in mine.dump.

**Comment by jjfiv** [comment]
The test looks good. You've raised a new detail:

Dividing by zero will need to throw an arithmetic error.

Right now we don't check anything - this will be in 'icodeExecute.js'

I'd like to just wrap this in as part of you implementing throw, if 
possible. Or make a new issue, whichever you'd rather.

**Comment by guptha-** [comment]
For divide by zero, we just need to implement catch for the default exception type thrown right? Do we need to do anything to actually throw it? Doesn't it happen automatically?

Edit: I see what you mean now.

**Comment by jjfiv** [comment]
javascript might throw some sort of exception automatically, but if it 
does, we'll have to catch it, and throw an 
"L/java/lang/ArithmeticException" appropriately. Since we're faking 
threads, we can't count on Javascript exceptions doing the work for us.

**Comment by etosch** [comment]
Updated code w/Dr Zaius, committed [here](https://github.com/jjfiv/dalvik-js/commit/0818fa014dafd4c7a8b836b3e1a76f19cbb50571), current bug appears to be in dexLoader parsing. Passing responsibility for this on to @jjfiv

**Comment by jjfiv** [comment]
I accidentally an array index. Fixed now.
