### ISSUE TITLE
make a list of the opcodes used by each of the test files

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#81]
To ensure opcode coverage, we need test files that call each of the opcodes. There are currently test files in tests and vmtest. We need documentation on the opcodes that our current test cases cover, as well as those that remain.

There is a cursory "icode" tracker written that can be modified (it hasn't been modified for several weeks now). The opcodes can also be read in disassembled dex files. The disassembler is part of the Android SDK. John can provide further guidance.

**Comment by jjfiv** [comment]
This is being automated in #41
