### ISSUE TITLE
move super inside invoke

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#83]
Move functionality at the top of icodeExecute inside the handlers, leveraging the **classLibrary** hidden global var. This var holds a reference to the last library loaded. It was a hack to make Instance able to learn its class without altering the constructor. I also tried adding a reference to ClassLibrary to the prototype chain, but this not only seemed philosophically incorrect, it didn't work because Class/Instance get loaded before VM. Since we don't instantiate the ClassLibrary to the VM, we can't go back and graft it on to the prototypes of already instantiated Instances (or at least that's my understanding of the matter).

**Comment by jjfiv** [comment]
I think you removed the hidden global variable, having glanced over the commits. Is this issue still relevant?

If that was another global, can we update the Instance constructor instead? I strongly feel this is a better option if possible.

**Comment by etosch** [comment]
Yeah, I didn't realize there was a ref to the VM inside each thread. I still think the super method should be compressed and shoved inside invoke. Right now it's a mosh posh of special cases, so it really needs to be cleaned up.

So are you saying you think it would be better to have a reference to the classLibrary inside the Instance constructor? My biggest qualm with that is that it's extra args we have to feed in that (a) could cause problems in updating existing code (unless we just have it as the last arg and "leverage" js's variable arg biz?) and (b) aren't being updated. Like, I think having something "in the background" that links things would be good. That was why I was trying to graft it into the prototype chain, which I know isn't right, but was a start. 

In any case, the following is the behavior I want. Upon loading up the VM, I want all classes in the purview of the VM to have a reference to the VM's classLibrary. However, I don't want to see it explicitly passed, since I don't want people fuxing with it. It'd be nice to have it as a black box, so that for a given Instance, I can just ask myself who my class is.

**Comment by jjfiv** [comment]
The only invocations of the "Instance" constructor, confirmed by grep is 
within "src/Class.js", so refactoring shouldn't be a problem at this 
point in the game. People should only make instances by going 
"someClass.makeNew" ... I think.

**Comment by jjfiv** [comment]
I think this is happy, too?

**Comment by etosch** [comment]
This can be closed; my issues with its current implemenetation will be
resolved with #89.

On Wed, Oct 31, 2012 at 12:30 PM, John Foley notifications@github.comwrote:

> I think this is happy, too?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/83#issuecomment-9951673.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch
