### ISSUE TITLE
something wrong with return

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#86]
the CheckCast test case has methods that return strings to be printed. These strings are being lost somewhere after the return call. Figure out where.

**Comment by etosch** [comment]
In the spec, the instruction is listed as holding the return value in a "value" register. In the code the return value is being accessed via a "src" register.

**Comment by jjfiv** [comment]
Is this done now?

**Comment by etosch** [comment]
it works for the CheckCast test, which was returning strings. Since types don't matter, I think it's fine.

How is the java ternary op implemented? Is that worth testing?

**Comment by jjfiv** [comment]
Should compile down to `cmp` and `goto`s or `if`s. Just syntactical sugar at the bytecode level. It will be calculated separately, and that register handed to the `return`.

I'll call it done.
