### ISSUE TITLE
test instance-of

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#88]
Develop a test that uses the instance-of opcode and verify that our implementation works.

**Comment by etosch** [comment]
It looks like the dest and src registers might be swapped (this was an issue earlier in the dalvik spec for some other instructions, right?).

**Comment by jjfiv** [comment]
Is this closed?

**Comment by etosch** [comment]
Yes, but it currently fails due to #99, which ought to be very high
priority.

On Wed, Oct 31, 2012 at 12:29 PM, John Foley notifications@github.comwrote:

> Is this closed?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/88#issuecomment-9951645.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch
