### ISSUE TITLE
make invoke less hideous

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#89]

**Comment by jjfiv** [comment]
Maybe a part of #91

**Comment by etosch** [comment]
Yeah...I almost think that, given the scale of what this might become, we ought to kick it to another file, like an invoke.js.

**Comment by etosch** [comment]
@jjfiv  - priority on this? Also, could you send a mail on tasks/priorities? Doesn't need to be too soon - focus on getting your IR stuff done. I can also do this tomorrow morning, if you let me know what you think the top goal in the next 24 hours is.

**Comment by jjfiv** [comment]
Invoke is less hideous now that it's in its own file, I believe?
@etosch

**Comment by etosch** [comment]
No, it's still abominable. The others might want to weigh in on its
readability.

On Wed, Oct 31, 2012 at 12:29 PM, John Foley notifications@github.comwrote:

> Invoke is less hideous now that it's in its own file, I believe?
> @etosch https://github.com/etosch
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/89#issuecomment-9951617.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by jjfiv** [comment]
Invoke was an ugly duckling, but matured into a beautiful swan.
