### ISSUE TITLE
fill-array-range test doesn't work

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#90]
Utilizes java.lang.Reflect in order to fill out a six-dimensional array. [Source](https://github.com/jjfiv/dalvik-js/blob/c0ceede189b1c6df13f72f1514bd566cabe9f7d7/sample/arraytest/FillArrayRange.java)

[Relevant Disassembly](https://github.com/jjfiv/dalvik-js/blob/c0ceede189b1c6df13f72f1514bd566cabe9f7d7/sample/arraytest/FillArrayRange.txt#L49)

This is lower priority than exceptions, stringbuilders, and threads.

**Comment by etosch** [comment]
Per the dalvik spec, I have an assert in `check-cast` to ensure that the thing being cast is a reference. However, for the array test, we're casting a primitive. Should we remove this condition for throwing a ClassCastException?
