### ISSUE TITLE
global abatement

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#93]
create a global.js to hold things of global interest. include in here typing info for classes, isA, etc.

**Comment by etosch** [comment]
Please everyone take a look at [global.js](https://github.com/jjfiv/dalvik-js/blob/master/src/global.js) and check my work. Some names for things have changed, but globals.js should be a fairly clear breakdown.

Please, however, EVERYONE take a look and make sure everything lines up with the code. I found numerous typo/version errors this weekend that I'm sure we've all made because JS fails silently. So if everyone would just take a quick look at this and double check, I'd appreciate it.

**Comment by etosch** [comment]
Post Threads, globals need to be updated. This will depend on issue #104. Right now isA isn't used anywhere on Threads, but if it is in the future without global.js being updated, it will fail.

**Comment by etosch** [comment]
@jjfiv SWIM should be assigned this; it's a good exercise for learning the new structure. Any questions regarding the new structure can be posted here.

**Comment by jjfiv** [comment]
I like globals.js
