### ISSUE TITLE
interface array type

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#94]
The class object has an instance array in it. What is the intended type of this array?

Also, link to next issue : testing interface implementation. (#95)

Finally, what's this :+1:

**Comment by jjfiv** [comment]
I believe dexloader fills it out with types.

**Comment by etosch** [comment]
Okay; I'm going to push this shortly. Wanted to get your opinion on some things. Think we ought to go into lockdown on some stuff - after this point I think we should have everyone stage their code in a branch before merging and the code should be reviewed before doing so. I'm trying to iron out some inconsistencies right now and I think separate branches here on out would be good for that.

**Comment by etosch** [comment]
Set this in [globals.js](https://github.com/jjfiv/dalvik-js/blob/master/src/global.js).
