### ISSUE TITLE
interface testing

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#95]
write a java program that tests interface implementation, as mentioned in #94

Also, what's this? :-1:

**Comment by jjfiv** [comment]
especially `invoke-interface`

**Comment by etosch** [comment]
Writing up a java file and the dexing this should take under an hour -- assign to Gupta? That should be fine for him if he doesn't have much time today. So what we would want is:

1) define an interface (since we don't want to have to deal with the standard library issue)
2) write a java class that implements that interface
3) dex those files 
4) test the dex'ed file using src/index.html
5) if this all turns out fine, close this issue; if not, describe in as much detail as you can the circumstances of the failure.

**Comment by etosch** [comment]
@jjfiv, what's the priority on this? No one is currently assigned.

**Comment by jjfiv** [comment]
Low, right now. I feel like it would conflict (possibly heavily) with invoke-super world #96.

**Comment by etosch** [comment]
Just ran the tests pushed in [this commit](https://github.com/jjfiv/dalvik-js/commit/9ff45357cae3a4c708e30e74ad2dd181352e3f97). `invoke-interface` isn't called. Given the way that `invoke-interface` is described in the [bytecode docs](http://source.android.com/tech/dalvik/dalvik-bytecode.html), it looks like there's some Java technique we'll need to test - like, implementing an interface on the fly? I'm looking for a reference on what we might want right now...

**Comment by jjfiv** [comment]
Maybe try some variations of

```
InterfaceA a = (InterfaceA) new A();
a.testInterface();
```

**Comment by etosch** [comment]
ready to close?

**Comment by etosch** [comment]
Testing added...over and out.
