### ISSUE TITLE
no Ljava/lang/Object; in ClassLibrary

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#98]
This object isn't loaded at all.

**Comment by jjfiv** [comment]
Doesn't seem to exist; we'll have to fake any references to it.

**Comment by etosch** [comment]
cool story, bro.

**Comment by etosch** [comment]
How about initializing ClassLibrary with a synthetic Ljava/lang/Object; ?

**Comment by jjfiv** [comment]
Whichever you feel more like doing.
