### ISSUE TITLE
thread hack causes other tests to fail

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#99]
I had the following problem with threads: when executing a method that called others thread, I'd run the pc down past all of the icodes and cause a failure due to a null reference when printing the status string. The hack can be seen [here](https://github.com/jjfiv/dalvik-js/blob/master/src/Thread.js#L119). However, this causes problems with [testSeveralMethods](https://github.com/jjfiv/dalvik-js/blob/master/tests/testSeveralMethods.java) and [instanceTest](https://github.com/jjfiv/dalvik-js/blob/master/tests/InstanceTest.java), since we are prematurely popping a method. A better solution for this issue needs to be found.

**Comment by jjfiv** [comment]
Put my gorilla paws all over your damn code again.
